export default {
  SET_PLAYLIST: 'SET_PLAYLIST',
  SET_OPTION: 'SET_JPLAYLIST_OPTION',
  ADD: 'ADD',
  REMOVE: 'REMOVE',
  CLEAR: 'CLEAR',
  SELECT: 'SELECT',
  PLAY: 'PLAY',
  PAUSE: 'PAUSE',
  SHUFFLE: 'SHUFFLE',
  NEXT: 'NEXT',
  PREVIOUS: 'PREVIOUS',
};
